package it.riccardoriggi.gooseform.enums;

public enum GooseComponentEnum {

	GOOSE_TEXT_AREA("GOOSE_TEXT_AREA"), GOOSE_SELECT("GOOSE_SELECT"), GOOSE_LINKED_SELECT("GOOSE_LINKED_SELECT"),
	GOOSE_DATA_LIST("GOOSE_DATA_LIST"), GOOSE_TEXT_FIELD("GOOSE_TEXT_FIELD"),
	GOOSE_PASSWORD_FIELD("GOOSE_PASSWORD_FIELD"), GOOSE_NUMBER_FIELD("GOOSE_NUMBER_FIELD"), GOOSE_RADIO("GOOSE_RADIO"),
	GOOSE_CHECKBOX("GOOSE_CHECKBOX"), GOOSE_EMAIL_FIELD("GOOSE_EMAIL_FIELD"), GOOSE_DATE_FIELD("GOOSE_DATE_FIELD"),
	GOOSE_DATE_TIME_FIELD("GOOSE_DATE_TIME_FIELD"), GOOSE_MONTH_FIELD("GOOSE_MONTH_FIELD"),
	GOOSE_WEEK_FIELD("GOOSE_WEEK_FIELD"), GOOSE_TIME_FIELD("GOOSE_TIME_FIELD"), GOOSE_TEL_FIELD("GOOSE_TEL_FIELD"),
	GOOSE_URL_FIELD("GOOSE_URL_FIELD"), GOOSE_COLOR_FIELD("GOOSE_COLOR_FIELD"), GOOSE_RANGE_FIELD("GOOSE_RANGE_FIELD");

	private final String text;

	GooseComponentEnum(final String text) {
		this.text = text;
	}

	public String getValue() {
		return text;
	}

}
